language: python
python:
 - "3.6"

branches:
 only:
  - master

before_install:
        - sudo apt-get update -qq 
        - sudo apt-get install -y iverilog

install:
 - python3 setup.py install

script:
 - ./test_all
