#!/usr/bin/env python3

import os
import sys

import chips_v.c_compile
from baremetal import *
from chips_v.soc import Soc
from chips_v.default_spec import default_settings


def run_test(filename):

    settings = default_settings
    address = 0x2000000
    for peripheral in settings["peripherals"]:
        peripheral.enumerate(address)
        address += 0x1000000
    instructions = chips_v.c_compile.read_binfile(filename)
    clk = Clock("clk")
    soc = Soc(clk, 1024 * 1024, instructions)
    return soc.simulate(10000)


for test in os.listdir("compliance_tests"):
    if test.endswith(".bin"):
        print("running", test)
        filename = os.path.join("compliance_tests", test)
        result = run_test(filename)
        if result:
            print("...pass")
        else:
            print("...fail")
            sys.exit(1)
sys.exit(0)
