#!/bin/bash

/opt/riscv/bin/riscv32-unknown-elf-gcc -Os -I ../include -march=rv32im -mcmodel=medlow -ffunction-sections -fdata-sections --specs=nosys.specs -c -o dhry1.o dhry_1.c
/opt/riscv/bin/riscv32-unknown-elf-gcc -Os -I ../include -march=rv32im -mcmodel=medlow -ffunction-sections -fdata-sections --specs=nosys.specs -c -o dhry2.o dhry_2.c
/opt/riscv/bin/riscv32-unknown-elf-gcc --specs=nosys.specs -c -o start.o start.S
/opt/riscv/bin/riscv32-unknown-elf-gcc -Wl,--gc-sections --specs=nosys.specs -nostartfiles -lc -lgcc -Tlink.ld -o dhry.elf dhry1.o dhry2.o start.o
#/opt/riscv/bin/riscv32-unknown-elf-objdump -d dhry2.o
##/opt/riscv/bin/riscv32-unknown-elf-objdump -S test.elf
/opt/riscv/bin/riscv32-unknown-elf-objcopy -S -O binary dhry.elf dhry.bin
python3 makehex.py dhry.bin dhry.hex
